### PR TITLE
fix(test): Enable using any client in config test

### LINKED ISSUE #255: Fix compiling Esplora client out of config test
While building `bdk-cli` inside a flake, I've got the following error:
```bash
> cargoCheckHook flags: -j 16 --profile release --features=repl\,sqlite\,rpc\,sp --target x86_64-unknown-linux-gnu --offline --
>    Compiling bdk-cli v2.0.0 (/build/gbaaz3igwf8dv2785f5vzxhnmhh5g41g-source)
> error[E0599]: no variant or associated item named `Esplora` found for enum `commands::ClientType` in the current scope
>    --> src/config.rs:211:50
>     |
> 211 |         assert_eq!(opts.client_type, ClientType::Esplora);
>     |                                                  ^^^^^^^ variant or associated item not found in `commands::ClientType`
>     |
>    ::: src/commands.rs:188:1
>     |
> 188 | pub enum ClientType {
>     | ------------------- variant or associated item `Esplora` not found for this enum
>
```

I'm not fully aware of what was being tested here, but this is causing cross incompatibilities with the features enabled for the enum and the features enabled for the assert.

_Originally posted by @nymius in https://github.com/bitcoindevkit/bdk-cli/pull/203#discussion_r2950019313_

### PR DESCRIPTION
**Pull request by tvpeter**
### Description

As pointed out in issue #255, whenever Esplora was configured out, the config test will fail because Esplora was used as the client.

This fix addresses the above issue by adding other client types in the test.

Fixes #255 

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk-cli/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [x] I've added tests to reproduce the issue which are now passing
* [x] I'm linking the issue being fixed by this PR

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -169,21 +169,43 @@ mod tests {
...
             #[cfg(any(feature = "electrum", feature = "esplora", feature = "rpc", feature = "cbf"))]
-            client_type: Some("esplora".to_string()),
+            client_type,
+
             #[cfg(any(feature = "electrum", feature = "esplora", feature = "rpc"))]
-            server_url: Some(" https://blockstream.info/testnet4/api".to_string()),
+            server_url: Some("https://example.com/testnet/api".to_string()),
             #[cfg(feature = "electrum")]
-            batch_size: None,
+            batch_size: Some(10),
```
Comment (nymius) [inline src/config.rs]: This is unnecessary as when compiling with electrum `Some(10)` is the default value that replaces the `None` value when calling `WalletOpts::try_into`.

File: src/config.rs [hunk 2]
```diff
@@ -169,21 +169,43 @@ mod tests {
 
     #[test]
     fn test_wallet_config_inner_to_opts_conversion() {
+        #[cfg(any(
```
Comment (nymius) [inline src/config.rs:174]: Is this necessary if using `cfg!` macro?

File: src/config.rs [hunk 3]
```diff
@@ -169,21 +169,43 @@ mod tests {
...
+
             #[cfg(any(feature = "electrum", feature = "esplora", feature = "rpc"))]
-            server_url: Some(" https://blockstream.info/testnet4/api".to_string()),
+            server_url: Some("https://example.com/testnet/api".to_string()),
             #[cfg(feature = "electrum")]
-            batch_size: None,
+            batch_size: Some(10),
             #[cfg(feature = "esplora")]
-            parallel_requests: None,
+            parallel_requests: Some(5),
```
Comment (nymius) [inline src/config.rs]: Same than above, `Some(5)` is the default value that replaces `None` value when calling `WalletOpts::try_into` if feature `esplora` is activated.

File: src/config.rs [hunk 4]
```diff
@@ -197,22 +219,18 @@ mod tests {
...
-        ))]
+        #[cfg(feature = "esplora")]
         assert_eq!(opts.client_type, ClientType::Esplora);
 
         #[cfg(feature = "sqlite")]
         assert_eq!(opts.database_type, DatabaseType::Sqlite);
 
+        assert_eq!(
+            opts.ext_descriptor,
+            "wpkh([07234a14/84'/1'/0']tpubDCSgT6PaVLQH9h2TAxKryhvkEurUBcYRJc9dhTcMDyahhWiMWfEWvQQX89yaw7w7XU8bcVujoALfxq59VkFATri3Cxm5mkp9kfHfRFDckEh/0/*)#429nsxmg"
```
Comment (nymius) [inline src/config.rs]: This would be a good moment to place these descriptors in `const`s at the beginning of the test module.

File: src/config.rs (hunk 2 above)
Comment (tvpeter) [reply src/config.rs:174]: Yes, else the clippy complains and errors out

File: src/config.rs [hunk 5]
```diff
@@ -197,22 +226,15 @@ mod tests {
...
-            "wpkh([07234a14/84'/1'/0']tpubDCSgT6PaVLQH9h2TAxKryhvkEurUBcYRJc9dhTcMDyahhWiMWfEWvQQX89yaw7w7XU8bcVujoALfxq59VkFATri3Cxm5mkp9kfHfRFDckEh/0/*)#429nsxmg"
-        );
 
-        #[cfg(any(
-            feature = "electrum",
-            feature = "esplora",
-            feature = "rpc",
-            feature = "cbf"
-        ))]
+        #[cfg(feature = "esplora")]
```
Comment (nymius) [inline src/config.rs]: Could you reuse something similar than the `if {} else {}` in line 180 to check each of the `client_types` with asserts?

Comment (tvpeter) [reply src/config.rs]: unfortunately `if ...else` blocks did did not work when testing all features.
